export const AMENITIES_OPTIONS = [
  "accessible boat dock",
  "accessible boat ramp",
  "accessible bock dock",
  "accessible campsites",
  "accessible drinking water",
  "accessible fishing dock",
  "accessible flush toilets",
  "accessible grills",
  "accessible handicapped site",
  "accessible hiking trails",
  "accessible parking",
  "accessible picnic area",
  "accessible picnic areas",
  "accessible picnic shelters",
  "accessible pit toilets",
  "accessible playground",
  "accessible restroom",
  "accessible scenic overlook",
  "accessible showers",
  "accessible site",
  "accessible sites",
  "accessible swimming",
  "accessible trails",
  "accessible vault toilet",
  "accessible vault toilets",
  "accessible walkways",
  "adirondack shelter",
  "amphitheater",
  "appalachian clubhouse",
  "archeological sites",
  "archery",
  "atm",
  "atv area",
  "axe",
  "bait shop",
  "bank",
  "baseball fields",
  "basketball court",
  "basketball courts",
  "bath house",
  "bathtub",
  "battery lights",
  "bay access",
  "beach",
  "beach access",
  "bear pole",
  "bed(s)",
  "bed(s) with mattress",
  "bike rentals",
  "bike trails",
  "biking",
  "birding",
  "boardwalk",
  "boat dock",
  "boat launch",
  "boat launch ramp",
  "boat ramp",
  "boat rental",
  "boat rentals",
  "boat slips",
  "boat storage",
  "boat trailer parking",
  "boat trips",
  "boating",
  "botanical gardens",
  "broom & dust pan",
  "bucket & shovel",
  "bunkbed(s)",
  "bunkbeds(s) with mattresses",
  "bus stop",
  "butterfly garden",
  "cafe",
  "camp host",
  "campfire circles",
  "campfire programs",
  "campfire rings",
  "campground host",
  "camping supplies",
  "canoe rentals",
  "canoeing",
  "cave tours",
  "cell phone service",
  "church",
  "cleaning equipment",
  "cleaning supplies",
  "clothes dryer",
  "clothesline",
  "coffee pot",
  "coin showers",
  "coleman lantern (fuel not provided)",
  "coleman stove (fuel not provided)",
  "comfort station",
  "community park",
  "concession (seasonal)",
  "concessions",
  "cooking area",
  "cooking pots",
  "cooking utensils",
  "corrals",
  "cot(s)",
  "couches",
  "courtesy dock",
  "covered parking",
  "creek access",
  "cultural activities",
  "cultural center",
  "day use area",
  "dining area",
  "disc golf course",
  "dock",
  "drinking water",
  "drinking water (hand pump)",
  "drinking water (peak season)",
  "dump station",
  "dumpster",
  "dvd player",
  "educational programs",
  "electric hook-up",
  "electric hookups",
  "electric stove",
  "electricity",
  "emergency phone",
  "emergency services",
  "entrance station",
  "equestrian sites",
  "event area",
  "fee booth",
  "fee station",
  "fire extinguisher",
  "fire finder",
  "fire pit",
  "fire rings",
  "fireplace",
  "firewood",
  "firewood vender",
  "firewood vendor",
  "first aid kit",
  "first aid station",
  "fish cleaning station",
  "fish cleaning stations",
  "fish hatchery",
  "fishing",
  "fishing cleaning stations",
  "fishing dock",
  "fishing guide",
  "fishing licenses",
  "fishing pier",
  "fishing river",
  "fitness trails",
  "flush toilet",
  "flush toilets",
  "flush toilets (seasonal)",
  "food storage locker",
  "fuel available",
  "futon(s)",
  "garbage cans",
  "garbage dumpster",
  "garbage service",
  "gatehouse",
  "general store",
  "geological attractions",
  "gift shop",
  "grill",
  "grills",
  "grocery store",
  "group camping",
  "group cooking facilities",
  "hand pump",
  "handicap access",
  "heater",
  "heating stove",
  "hiking",
  "hiking trail",
  "historic sites",
  "hitching racks",
  "horse corrals",
  "horse rentals",
  "horse staging area",
  "horse stalls",
  "horse watering station",
  "horseback riding",
  "horseback riding trails",
  "horseshoe pit",
  "horseshoe pits",
  "horseshoes",
  "hospital",
  "host",
  "host site",
  "hot springs",
  "hot water",
  "ice",
  "ice machine",
  "information",
  "information board",
  "information center",
  "interpretive trails",
  "kayak rentals",
  "kayaking",
  "kennel",
  "kitchen",
  "kitchen (no water)",
  "lake access",
  "lantern",
  "lantern posts",
  "laundry facilities",
  "lifeguards",
  "lighthouse",
  "lighthouse tours",
  "lights",
  "loder trail entrance",
  "lookout tower",
  "marina",
  "mattress pad(s)",
  "meat shed",
  "men's restroom/shower",
  "microwave",
  "mop",
  "motor boat rentals",
  "motorcycle trails",
  "multi-use court",
  "museum",
  "non-motorized boating",
  "non-potable water",
  "off-road vehicle rentals",
  "off-road vehicle trails",
  "outdoor showers",
  "outfitter guide services",
  "outhouse",
  "oven",
  "park attendant",
  "park office",
  "parking",
  "parking (day use lot)",
  "parking area",
  "paved parking",
  "paved pathways",
  "paved roads",
  "paved sites",
  "pavilion",
  "pay phone",
  "pay station",
  "pets allowed",
  "picnic area",
  "picnic pavilion",
  "picnic shelter",
  "picnic shelters",
  "picnic table",
  "picnic tables",
  "picnicing",
  "pit toilet",
  "pit toilets",
  "playgroiund",
  "playground",
  "pontoon rental",
  "portable toilets",
  "propane",
  "propane fireplace",
  "propane fuel available",
  "propane grills",
  "propane heat",
  "propane lantern",
  "propane lantern (fuel not provided)",
  "propane lights",
  "propane oven",
  "propane refridgerator",
  "propane stove",
  "public hydrant",
  "rain catchment barrel",
  "ranger station",
  "recreation center",
  "recycle containers",
  "recycling",
  "refrigerator",
  "refuse containers",
  "restaurant",
  "restroom",
  "restrooms",
  "restrooms (flush toilet)",
  "river access",
  "rv parking",
  "rv sanitary dump station",
  "rv supplies",
  "scenic drive",
  "scenic overlooks",
  "security lights",
  "self pay station",
  "self-pay station",
  "sewer hookup",
  "sewer hookups",
  "shade",
  "shooting range",
  "shower",
  "showers",
  "showers (seasonal)",
  "shuttle bus service",
  "skiing",
  "sleeping shelter",
  "small refridgerator",
  "smoke alarm",
  "snow park",
  "snow shovel",
  "soccer fields",
  "softball fields",
  "spence cabin",
  "stable",
  "stock watering tank",
  "swimming",
  "swimming pool",
  "table & benches",
  "table & chairs",
  "tables",
  "telephone",
  "tennis courts",
  "tent pad",
  "tent pads",
  "tent sites",
  "toilet accessible",
  "toilet flush",
  "toilet pit/vault",
  "trailhead",
  "trailhead parking",
  "trailheads",
  "trails",
  "trash collection",
  "trash dumpsters",
  "twin bed platform",
  "twin bed(s)",
  "utility sinks",
  "vault toilet",
  "vault toilets",
  "vending machines",
  "viewing platform/overlk",
  "visitor center",
  "visitors center",
  "volleyball court",
  "volleyball courts",
  "walk-in freezer",
  "washer & dryer",
  "water",
  "water (seasonal)",
  "water drinking",
  "water faucets",
  "water hookups",
  "water hydrant",
  "water spigot",
  "water troughs",
  "waterfront sites",
  "wildlife viewing",
  "wind shelters",
  "wireless internet",
  "women's restroom/shower",
  "wood stove",
];

export const ACTIVITIES_OPTIONS = [
  "accessible swimming",
  "amphitheater",
  "antiquing",
  "archery",
  "auto touring",
  "backpacking",
  "badminton",
  "beach camping",
  "beachcombing",
  "berry picking",
  "biking",
  "bird watching",
  "birding",
  "boat rental",
  "boating",
  "camping",
  "canoeing",
  "caving",
  "clam digging",
  "climbing",
  "crabbing",
  "crawfishing",
  "cross country skiing",
  "cultural activities",
  "day use area",
  "disc golf",
  "diving",
  "downhill skiing",
  "educational programs",
  "emergency services",
  "environmental education",
  "evening programs",
  "fire lookouts/cabins overnight",
  "fish hatchery",
  "fish viewing site",
  "fishing",
  "gold panning",
  "golf",
  "gondola rides",
  "guided interpretive walks",
  "hiking",
  "hiking trail",
  "historic & cultural site",
  "historic sites",
  "horse camping",
  "horseback riding",
  "hotel/lodge/resort fs owned",
  "hotel/lodge/resort privately owned",
  "hunting",
  "ice climbing",
  "ice fishing",
  "ice skating",
  "information site",
  "interpretive programs",
  "jet skiing",
  "kayaking",
  "lookout tower",
  "marina",
  "motel",
  "motor boat",
  "mountain biking",
  "mountain climbing",
  "museum",
  "mushroom picking",
  "non-motorized boating",
  "observation site",
  "off highway vehicle",
  "off highway vehicle trails",
  "off road vehicle trails",
  "organization site fs owned",
  "other recreation concession site",
  "paddle boating",
  "paddling",
  "photography",
  "picnic tables",
  "picnicking",
  "playground park specialized sport site",
  "rafting",
  "ranger station",
  "recreation programs",
  "recreation residence",
  "recreational shooting",
  "recreational vehicles",
  "river trips",
  "rock climbing",
  "sailboarding",
  "sailing",
  "scenic drive",
  "scuba diving",
  "sea kayaking",
  "shuffle board",
  "skiing",
  "sledding",
  "snorkeling",
  "snow tubing",
  "snowboarding",
  "snowmobile",
  "snowmobile trails",
  "snowmobiling",
  "snowshoeing",
  "soccer fields",
  "softball fields",
  "star gazing",
  "stargazing",
  "surfing",
  "swimming",
  "swimming site",
  "trails all terrain/ohv",
  "trails difficult hiking",
  "trails horse",
  "tubing",
  "visitor center",
  "water access",
  "water activities",
  "water skiing",
  "water sports",
  "whale watching",
  "whitewater rafting",
  "wild horse viewing",
  "wilderness",
  "wildlife viewing",
  "windsurfing",
  "winery tours",
  "winter sports",
  "wood cutting",
];

export const ATTRIBUTES_OPTIONS = [
  { label: "campfire allowed", type: "boolean" },
  { label: "driveway length", type: "number" },
  { label: "accessible campsite", type: "none" },
  { label: "driveway surface", type: "string" },
  { label: "first aid kit", type: "none" },
  { label: "num of beds", type: "number" },
  { label: "concessions", type: "boolean" },
  { label: "hitching racks", type: "none" },
  { label: "host", type: "boolean" },
  { label: "clothes dryer", type: "none" },
  { label: "accessible campsites", type: "none" },
  { label: "hot water", type: "none" },
  { label: "emergency services", type: "none" },
  { label: "propane oven", type: "none" },
  { label: "softball fields", type: "none" },
  { label: "security lights", type: "none" },
  { label: "trailhead parking", type: "none" },
  { label: "grills/fire ring", type: "boolean" },
  { label: "portable toilets", type: "none" },
  { label: "paved pathways", type: "none" },
  { label: "dock", type: "none" },
  { label: "double driveway", type: "boolean" },
  { label: "couches", type: "none" },
  { label: "table & chairs", type: "none" },
  { label: "small campsite", type: "none" },
  { label: "accessibility", type: "none" },
  { label: "accessible showers", type: "none" },
  { label: "dump station", type: "boolean" },
  { label: "canoe rentals", type: "none" },
  { label: "kennel", type: "none" },
  { label: "sewer hookups", type: "none" },
  { label: "tent pad width", type: "string" },
  { label: "horse hitching post", type: "boolean" },
  { label: "wireless internet", type: "none" },
  { label: "non-potable water", type: "none" },
  { label: "dvd", type: "none" },
  { label: "boardwalk", type: "none" },
  { label: "ice machine", type: "none" },
  { label: "propane lantern (fuel not provided)", type: "none" },
  { label: "restaurant", type: "boolean" },
  { label: "water (seasonal)", type: "none" },
  { label: "propane", type: "none" },
  { label: "twin bed platform", type: "none" },
  { label: "fishing licenses", type: "none" },
  { label: "site length", type: "string" },
  { label: "boat trips", type: "none" },
  { label: "day use area", type: "none" },
  { label: "shower/bath type", type: "string" },
  { label: "church", type: "none" },
  { label: "boat maintenance", type: "none" },
  { label: "drinking water", type: "boolean" },
  { label: "non smoking", type: "none" },
  { label: "washer & dryer", type: "none" },
  { label: "accessible vault toilets", type: "none" },
  { label: "air conditioning", type: "none" },
  { label: "porch", type: "string" },
  { label: "smoke alarm", type: "none" },
  { label: "general store", type: "boolean" },
  { label: "cave tours", type: "none" },
  { label: "ice", type: "none" },
  { label: "lighting", type: "string" },
  { label: "marina", type: "none" },
  { label: "propane stove", type: "none" },
  { label: "is equipment mandatory", type: "boolean" },
  { label: "clothes-washer", type: "none" },
  { label: "group allowed", type: "none" },
  { label: "snow shovel", type: "none" },
  { label: "propane heat", type: "none" },
  { label: "fish cleaning stations", type: "none" },
  { label: "propane heating", type: "none" },
  { label: "fridge", type: "none" },
  { label: "base number of people", type: "number" },
  { label: "clothes-line", type: "boolean" },
  { label: "bbq", type: "boolean" },
  { label: "sleeping shelter", type: "none" },
  { label: "supplies", type: "string" },
  { label: "horse watering station", type: "none" },
  { label: "group cooking facilities", type: "none" },
  { label: "mattress pad(s)", type: "none" },
  { label: "microwave", type: "none" },
  { label: "lifeguards", type: "none" },
  { label: "shade", type: "string" },
  { label: "clothes-dryer", type: "none" },
  { label: "playground", type: "none" },
  { label: "propane fireplace", type: "none" },
  { label: "drinking water (peak season)", type: "none" },
  { label: "boat included", type: "none" },
  { label: "coleman lantern (fuel not provided)", type: "none" },
  { label: "drinking water (hand pump)", type: "none" },
  { label: "tent pads", type: "none" },
  { label: "satellite tv access", type: "boolean" },
  { label: "bus stop", type: "none" },
  { label: "camping supplies", type: "none" },
  { label: "driveway entry", type: "string" },
  { label: "food storage locker", type: "none" },
  { label: "bait shop", type: "none" },
  { label: "fuel available", type: "none" },
  { label: "futon(s)", type: "none" },
  { label: "oven", type: "none" },
  { label: "accessible picnic shelters", type: "none" },
  { label: "vault toilets", type: "none" },
  { label: "radio", type: "none" },
  { label: "wind shelters", type: "none" },
  { label: "historic sites", type: "none" },
  { label: "rv storage", type: "none" },
  { label: "water troughs", type: "none" },
  { label: "type of site access", type: "string" },
  { label: "water spigot", type: "boolean" },
  { label: "pit toilets", type: "none" },
  { label: "motorcycle trails", type: "none" },
  { label: "volleyball courts", type: "none" },
  { label: "bunkbed(s)", type: "none" },
  { label: "min num of people", type: "number" },
  { label: "driveway grade", type: "string" },
  { label: "lantern", type: "none" },
  { label: "small refrigerator", type: "none" },
  { label: "boat ramp", type: "none" },
  { label: "fishing guide", type: "none" },
  { label: "site height", type: "string" },
  { label: "has rentals", type: "string" },
  { label: "base number of vehicles", type: "number" },
  { label: "bear pole", type: "none" },
  { label: "stock watering tank", type: "none" },
  { label: "outdoor cooler box", type: "none" },
  { label: "casino", type: "none" },
  { label: "motor boat rentals", type: "none" },
  { label: "shooting range", type: "none" },
  { label: "max num of vehicles", type: "number" },
  { label: "firewood vendor", type: "none" },
  { label: "accessible walkways", type: "none" },
  { label: "electric heating", type: "none" },
  { label: "full hookup", type: "string" },
  { label: "accessible trails", type: "none" },
  { label: "trailheads", type: "none" },
  { label: "gas heating", type: "none" },
  { label: "oil heating", type: "none" },
  { label: "dvd player", type: "none" },
  { label: "horse staging area", type: "none" },
  { label: "propane lights", type: "none" },
  { label: "living room", type: "none" },
  { label: "anchorage", type: "none" },
  { label: "first aid station", type: "none" },
  { label: "checkout time", type: "string" },
  { label: "cooking area", type: "none" },
  { label: "is double driveway", type: "boolean" },
  { label: "accessible boat ramp", type: "none" },
  { label: "cleaning equipment", type: "none" },
  { label: "atm", type: "none" },
  { label: "paved sites", type: "none" },
  { label: "near water", type: "boolean" },
  { label: "accessible playground", type: "none" },
  { label: "river access", type: "none" },
  { label: "lantern posts", type: "none" },
  { label: "pets allowed", type: "string" },
  { label: "max vehicle length", type: "string" },
  { label: "category", type: "string" },
  { label: "sewer hookup", type: "none" },
  { label: "trash collection", type: "none" },
  { label: "site width", type: "string" },
  { label: "saw", type: "none" },
  { label: "utility sinks", type: "none" },
  { label: "showers (seasonal)", type: "none" },
  { label: "bed type", type: "string" },
  { label: "pontoon rental", type: "none" },
  { label: "mop", type: "none" },
  { label: "bay access", type: "none" },
  { label: "fire ring", type: "none" },
  { label: "axe", type: "none" },
  { label: "bucket & shovel", type: "none" },
  { label: "capacity rating", type: "string" },
  { label: "archeological sites", type: "none" },
  { label: "battery lights", type: "none" },
  { label: "picnic area", type: "none" },
  { label: "stove/oven", type: "none" },
  { label: "refrigerator", type: "none" },
  { label: "num rooms", type: "number" },
  { label: "lake access", type: "none" },
  { label: "grills", type: "boolean" },
  { label: "tent pad length", type: "string" },
  { label: "heating stove", type: "none" },
  { label: "lookout tower", type: "none" },
  { label: "beach access", type: "none" },
  { label: "proximity to water", type: "string" },
  { label: "food locker", type: "boolean" },
  { label: "geological attractions", type: "none" },
  { label: "horseshoe pit", type: "none" },
  { label: "outdoor showers", type: "none" },
  { label: "electric hookups 50 amp", type: "none" },
  { label: "table & benches", type: "none" },
  { label: "waterfront sites", type: "none" },
  { label: "hike in distance to site", type: "string" },
  { label: "generator free", type: "none" },
  { label: "cabin electricity", type: "none" },
  { label: "multi-use court", type: "none" },
  { label: "location rating", type: "string" },
  { label: "max num of horses", type: "number" },
  { label: "fax hookup", type: "boolean" },
  { label: "telephone hookup", type: "boolean" },
  { label: "kitchen (no water)", type: "none" },
  { label: "fireplace", type: "none" },
  { label: "quiet area", type: "boolean" },
  { label: "accessible occupant message", type: "none" },
  { label: "condition rating", type: "string" },
  { label: "cabin heating", type: "string" },
  { label: "creek access", type: "none" },
  { label: "manure disposal", type: "none" },
  { label: "electricity", type: "none" },
  { label: "broom & dust pan", type: "none" },
  { label: "boat storage", type: "none" },
  { label: "grocery store", type: "none" },
  { label: "accessible scenic overlook", type: "none" },
  { label: "coffee pot", type: "none" },
  { label: "checkin time", type: "string" },
  { label: "tent pad", type: "boolean" },
  { label: "cooking utensils", type: "none" },
  { label: "fenced pastures", type: "none" },
  { label: "furnished", type: "none" },
  { label: "coin showers", type: "boolean" },
  { label: "platform", type: "boolean" },
  { label: "off-road vehicle trails", type: "none" },
  { label: "table", type: "none" },
  { label: "site reserve type", type: "string" },
  { label: "community park", type: "none" },
  { label: "horse corrals", type: "none" },
  { label: "bed(s) with mattress", type: "none" },
  { label: "toilet", type: "none" },
  { label: "visitor center", type: "boolean" },
  { label: "fishing dock", type: "none" },
  { label: "rain catchment barrel", type: "none" },
  { label: "fridge with freezer", type: "none" },
  { label: "boat slips", type: "none" },
  { label: "horseback riding trails", type: "none" },
  { label: "tennis courts", type: "none" },
  { label: "rv supplies", type: "none" },
  { label: "shuttle bus service", type: "none" },
  { label: "picnic tables", type: "none" },
  { label: "cot(s)", type: "none" },
  { label: "television", type: "none" },
  { label: "wood stove", type: "none" },
  { label: "electric stove", type: "none" },
  { label: "amphitheater", type: "boolean" },
  { label: "horse stalls", type: "none" },
  { label: "event area", type: "none" },
  { label: "bed(s)", type: "none" },
  { label: "picnic shelters", type: "none" },
  { label: "cable tv access", type: "boolean" },
  { label: "horse stall/corral", type: "boolean" },
  { label: "bathtub", type: "none" },
  { label: "accessible pit toilets", type: "none" },
  { label: "laundry facilities", type: "none" },
  { label: "heater", type: "none" },
  { label: "pay phone", type: "none" },
  { label: "clothesline", type: "none" },
  { label: "boat rentals", type: "none" },
  { label: "fire extinguisher", type: "none" },
  { label: "accessible sites", type: "none" },
  { label: "site rating", type: "string" },
  { label: "rv parking", type: "none" },
  { label: "parking area", type: "boolean" },
  { label: "accessible fishing dock", type: "none" },
  { label: "firewood", type: "none" },
  { label: "placed on map", type: "boolean" },
  { label: "dining area", type: "none" },
  { label: "campfire circles", type: "none" },
  { label: "self pay station", type: "none" },
  { label: "water hookup", type: "boolean" },
  { label: "accessible parking", type: "none" },
  { label: "playgroiund", type: "none" },
  { label: "baseball fields", type: "none" },
  { label: "lantern pole", type: "none" },
  { label: "entrance station", type: "none" },
  { label: "educational programs", type: "none" },
  { label: "cleaning supplies", type: "none" },
  { label: "tables", type: "none" },
  { label: "coleman stove (fuel not provided)", type: "none" },
  { label: "scenic overlooks", type: "none" },
  { label: "ranger station", type: "none" },
  { label: "paved roads", type: "none" },
  { label: "deck", type: "none" },
  { label: "telephone", type: "none" },
  { label: "internet access", type: "boolean" },
  { label: "lighthouse", type: "none" },
  { label: "soccer fields", type: "none" },
  { label: "emergency phone", type: "boolean" },
  { label: "accessible drinking water", type: "none" },
  { label: "campfire rings", type: "none" },
  { label: "propane lantern", type: "none" },
  { label: "stove/fridge", type: "string" },
  { label: "kitchen", type: "none" },
  { label: "butterfly garden", type: "none" },
  { label: "fitness trails", type: "none" },
  { label: "lights", type: "none" },
  { label: "flush toilets (seasonal)", type: "none" },
  { label: "max num of people", type: "number" },
  { label: "kayak rentals", type: "none" },
  { label: "adirondack shelter", type: "none" },
  { label: "accessible bock dock", type: "none" },
  { label: "showers", type: "none" },
  { label: "outhouse", type: "none" },
  { label: "picnic table", type: "boolean" },
  { label: "propane refrigerator", type: "none" },
  { label: "fire pit", type: "boolean" },
  { label: "accessible grills", type: "none" },
  { label: "privacy", type: "boolean" },
  { label: "cooking pots", type: "none" },
  { label: "boat trailer parking", type: "none" },
  { label: "boat dock", type: "none" },
  { label: "paved parking", type: "none" },
  { label: "woodstove/fireplace", type: "none" },
  { label: "propane grills", type: "none" },
  { label: "bunkbeds(s) with mattresses", type: "none" },
  { label: "interpretive trails", type: "none" },
  { label: "corrals", type: "none" },
  { label: "twin bed(s)", type: "none" },
  { label: "dish-washer", type: "none" },
  { label: "lean to/shelter", type: "boolean" },
  { label: "wood heating", type: "none" },
  { label: "electricity hookup", type: "string" },
  { label: "accessible picnic area", type: "none" },
  { label: "accessible flush toilets", type: "none" },
  { label: "min num of vehicles", type: "number" },
  { label: "map number", type: "string" },
  { label: "fish hatchery", type: "none" },
  { label: "basketball courts", type: "none" },
  { label: "cell phone service", type: "none" },
  { label: "flush toilets", type: "none" },
  { label: "off-road vehicle rentals", type: "none" },
  { label: "gift shop", type: "boolean" },
  { label: "campfire programs", type: "none" },
  { label: "recycling", type: "none" },
  { label: "meat shed", type: "none" },
  { label: "fishing pier", type: "none" },
];
